[package]
name = "freenectrs"
version = "0.1.0"
authors = ["Entscheider <email>"]

[dependencies]
libc = "0.2"

[dev-dependencies]
image = "0.12"
[dev-dependencies.glwinhelp]
git = "https://github.com/Entscheider/glwinhelp"
