[package]
name = "glwinhelp"
version = "0.1.0"

[dependencies]
genmesh = "0.4"
obj = { version = "0.5", features = ["usegenmesh"] }
image = "0.12"

[dependencies.glium]
version = "0.16"
#default-features = false
